package coder

import (
	"bytes"
	"context"
	"fmt"
	"strings"
	"text/template"

	"github.com/hollow/gopherlens/pkg/types"
)

// Agent generates valid Go _test.go files from test specifications,
// following table-driven test patterns with testify/mock and sqlmock.
type Agent struct{}

func New() *Agent { return &Agent{} }

const testFileTemplate = `// Code generated by GopherLens; DO NOT EDIT.

package {{.Package}}

import (
	"testing"

	"github.com/DATA-DOG/go-sqlmock"
	"github.com/stretchr/testify/assert"
	"fmt"
	"github.com/stretchr/testify/mock"
{{range .Imports}}
	"{{.}}"
{{end}}
)

{{range $mock := .Mocks}}
// {{$mock.Name}} is a mock for {{$mock.Interface}}.
type {{$mock.Name}} struct {
	mock.Mock
}

{{range $mock.Methods}}
func (m *{{$mock.Name}}) {{.Name}}({{.Args}}) {{.Returns}} {
	args := m.Called({{.ArgNames}})
	{{if .ReturnCount | eq 2}}
	return args.Get(0).({{.Return0Cast}}), args.Error(1)
	{{else}}
	return args.Get(0).({{.Return0Cast}})
	{{end}}
}
{{end}}
{{end}}

func {{.TestFuncName}}(t *testing.T) {
	tests := []struct {
		name    string
		setup   func(mockDB sqlmock.Sqlmock)
		wantErr bool
		wantStatus int
	}{
{{range .Cases}}
		{
			name: "{{.Name}}",
			setup: func(mockDB sqlmock.Sqlmock) {
				{{.SetupBody}}
			},
			wantErr: {{.ExpectError}},
			wantStatus: {{.ExpectStatus}},
		},
{{end}}
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			db, mockDB, err := sqlmock.New()
			if err != nil {
				t.Fatalf("failed to create sqlmock: %v", err)
			}
			defer db.Close()

			if tt.setup != nil {
				tt.setup(mockDB)
			}

			// TODO: invoke the actual function under test
			_ = db

			if tt.wantErr {
				assert.Error(t, err)
			} else {
				assert.NoError(t, err)
			}
		})
	}
}
`

type templateData struct {
	Package      string
	Imports      []string
	Mocks        []mockDef
	TestFuncName string
	Cases        []caseData
}

type mockDef struct {
	Name      string
	Interface string
	Methods   []mockMethod
}

type mockMethod struct {
	Name        string
	Args        string
	ArgNames    string
	Returns     string
	ReturnCount int
	Return0Cast string
}

type caseData struct {
	Name        string
	SetupBody   string
	ExpectError bool
	ExpectStatus int
}

// Generate produces a complete _test.go file from the test matrix.
func (a *Agent) Generate(ctx context.Context, matrix *types.TestMatrix, arch *types.ArchitectureResult) (*types.GeneratedTest, error) {
	if matrix == nil || len(matrix.Cases) == 0 {
		return nil, fmt.Errorf("no test cases to generate")
	}

	data := buildTemplateData(matrix, arch)

	var buf bytes.Buffer
	tmpl, err := template.New("test").Funcs(template.FuncMap{
		"eq": func(a, b int) bool { return a == b },
	}).Parse(testFileTemplate)
	if err != nil {
		return nil, fmt.Errorf("parse template: %w", err)
	}

	if err := tmpl.Execute(&buf, data); err != nil {
		return nil, fmt.Errorf("execute template: %w", err)
	}

	return &types.GeneratedTest{
		FilePath:    arch.TargetFile[:len(arch.TargetFile)-3] + "_test.go",
		Content:     buf.String(),
		PackageName: data.Package,
	}, nil
}

// Fix updates a generated test to address failures reported by the Validator.
func (a *Agent) Fix(ctx context.Context, test *types.GeneratedTest, failures *types.ValidationResult) (*types.GeneratedTest, error) {
	// In a full implementation, this would parse the failure output,
	// identify which test cases failed, and adjust mock setups or assertions.
	// For now, return the test unchanged with a note.
	test.Content = "// FIXME: auto-fix not yet implemented, test needs manual adjustment\n" + test.Content
	return test, nil
}

func buildTemplateData(matrix *types.TestMatrix, arch *types.ArchitectureResult) templateData {
	data := templateData{
		Package:      "main",
		TestFuncName: fmt.Sprintf("Test%sGenerated", matrix.TargetFunction),
		Imports:      []string{},
	}

	// Build mock definitions from external dependencies only
	mockKinds := map[types.DependencyKind]bool{types.DepSQL: true, types.DepHTTP: true, types.DepRedis: true, types.DepGRPC: true}
	kindImports := map[types.DependencyKind]string{
		types.DepSQL:   "database/sql",
		types.DepHTTP:  "net/http",
		types.DepRedis: "github.com/redis/go-redis/v9",
		types.DepGRPC:  "google.golang.org/grpc",
	}
	seenKinds := make(map[types.DependencyKind]bool)
	addedImports := make(map[string]bool)

	for _, dep := range arch.Dependencies {
		if !mockKinds[dep.Kind] || seenKinds[dep.Kind] {
			continue
		}
		seenKinds[dep.Kind] = true

		if imp, ok := kindImports[dep.Kind]; ok && !addedImports[imp] {
			addedImports[imp] = true
			data.Imports = append(data.Imports, imp)
		}

		methods := mockMethodsForKind(dep.Kind)
		data.Mocks = append(data.Mocks, mockDef{
			Name:      fmt.Sprintf("Mock%s", strings.Title(string(dep.Kind))),
			Interface: string(dep.Kind),
			Methods:   methods,
		})
	}

	// Build test case data
	for _, tc := range matrix.Cases {
		setupBody := buildSetupBody(tc)
		data.Cases = append(data.Cases, caseData{
			Name:        tc.Name,
			SetupBody:   setupBody,
			ExpectError: tc.ExpectError,
			ExpectStatus: tc.ExpectStatus,
		})
	}

	return data
}

func mockMethodsForKind(kind types.DependencyKind) []mockMethod {
	switch kind {
	case types.DepSQL:
		return []mockMethod{
			{
				Name:        "QueryRow",
				Args:        "query string, args ...interface{}",
				ArgNames:    "query, args",
				Returns:     "(*sql.Row, error)",
				ReturnCount: 2,
				Return0Cast: "*sql.Row",
			},
		}
	case types.DepHTTP:
		return []mockMethod{
			{
				Name:        "Do",
				Args:        "req *http.Request",
				ArgNames:    "req",
				Returns:     "(*http.Response, error)",
				ReturnCount: 2,
				Return0Cast: "*http.Response",
			},
		}
	case types.DepRedis:
		return []mockMethod{
			{
				Name:        "Get",
				Args:        "key string",
				ArgNames:    "key",
				Returns:     "(string, error)",
				ReturnCount: 2,
				Return0Cast: "string",
			},
		}
	case types.DepGRPC:
		return []mockMethod{
			{
				Name:        "Invoke",
				Args:        "ctx context.Context, method string, args, reply interface{}",
				ArgNames:    "ctx, method, args, reply",
				Returns:     "error",
				ReturnCount: 1,
				Return0Cast: "error",
			},
		}
	default:
		return nil
	}
}

func buildSetupBody(tc types.TestCase) string {
	if tc.ExpectError {
		return fmt.Sprintf("// Simulate %s\n\t\t\t\tmockDB.ExpectQuery(\".*\").WillReturnError(fmt.Errorf(\"mock error\"))", tc.Description)
	}
	return fmt.Sprintf("// Happy path: %s\n\t\t\t\tmockDB.ExpectQuery(\".*\").WillReturnRows(sqlmock.NewRows([]string{\"id\"}).AddRow(1))", tc.Description)
}
